## [source link](https://www.tensorflow.org/guide/tensor)

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

2023-02-17 08:08:52.815238: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-17 08:08:52.865115: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-17 08:08:52.865974: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-17 08:08:52.869309: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [5]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [7]:
#convet to numpy array
np.array(a)
a.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [16]:
#typical tensor shape
#(batach x Height x width x feature)
#(axis0, axis1, axis2, axis3)

In [9]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


Tensors have shapes.  Some vocabulary:

* **Shape**: The length (number of elements) of each of the axes of a tensor.
* **Rank**: Number of tensor axes.  A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product of the shape vector's elements.


In [15]:
rank_4_tensor = tf.zeros([5, 2, 4, 5])
print("Type of every element:", rank_4_tensor.dtype) # does not return tensor
print("Number of axes:", rank_4_tensor.ndim) # does not return tensor --> rank
print("Shape of tensor:", rank_4_tensor.shape) # does not return tensor
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0]) # does not return tensor
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1]) # does not return tensor
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy()) # does not return tensor


#### REturn a tensor #######
print(tf.rank(rank_4_tensor))
print(tf.shape(rank_4_tensor))

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (5, 2, 4, 5)
Elements along axis 0 of tensor: 5
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  200
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([5 2 4 5], shape=(4,), dtype=int32)


### Single-axis indexing

TensorFlow follows standard Python indexing rules, similar to [indexing a list or a string in Python](https://docs.python.org/3/tutorial/introduction.html#strings){:.external}, and the basic rules for NumPy indexing.

* indexes start at `0`
* negative indices count backwards from the end
* colons, `:`, are used for slices: `start:stop:step`


In [17]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print("Second column:", rank_2_tensor[:, 1].numpy())


Second column: [2. 4. 6.]


## Reshaping
The `tf.reshape` operation is fast and cheap as the underlying data does not need to be duplicated

In [21]:
x = tf.constant([[1], [2], [3]])
reshaped = tf.reshape(x, [1, 3])