## Tesnor Tutorial [source link](https://www.tensorflow.org/guide/tensor)

## numpy basics [link](https://numpy.org/devdocs/user/absolute_beginners.html)

In [1]:
import tensorflow as tf
import numpy as np

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


## Tensor and numpy have same "axis" idea


In [8]:
x = np.arange(24).reshape([2, 3, 4]) # axis0 = 2, axis1=3, axis2=axis-1=4
print('x=')
print(x)
print()

#when we do an operation across a specific axis that meeans -->>>>> REMOVE IT
y = np.sum(x, axis=0) # that means remove axis 0 (2, 3, 4) becomes (3, 4)
print('across axis: 0')
print(y)
print()

y = np.sum(x, axis=1) # that means remove axis 0 (2, 3, 4) becomes (2, 4)
print('across axis: 1')
print(y)
print()

y = np.sum(x, axis=(1,2)) # that means remove axis 0 (2, 3, 4) becomes (2,)
print('across axis: 1, 2')
print(y)
print()



x=
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

across axis: 0
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

across axis: 1
[[12 15 18 21]
 [48 51 54 57]]

across axis: 1, 2
[ 66 210]



In [8]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [9]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [10]:
#convet to numpy array
np.array(a)
a.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [11]:
#typical tensor shape
#(batach x Height x width x feature)
#(axis0, axis1, axis2, axis3)

In [14]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


Tensors have shapes.  Some vocabulary:

* **Shape**: The length (number of elements) of each of the axes of a tensor.
* **Rank**: Number of tensor axes.  A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product of the shape vector's elements.


In [15]:
rank_4_tensor = tf.zeros([5, 2, 4, 5])
print("Type of every element:", rank_4_tensor.dtype) # does not return tensor
print("Number of axes:", rank_4_tensor.ndim) # does not return tensor --> rank
print("Shape of tensor:", rank_4_tensor.shape) # does not return tensor
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0]) # does not return tensor
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1]) # does not return tensor
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy()) # does not return tensor


#### REturn a tensor #######
print(tf.rank(rank_4_tensor))
print(tf.shape(rank_4_tensor))

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (5, 2, 4, 5)
Elements along axis 0 of tensor: 5
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  200
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([5 2 4 5], shape=(4,), dtype=int32)


### Single-axis indexing

TensorFlow follows standard Python indexing rules, similar to [indexing a list or a string in Python](https://docs.python.org/3/tutorial/introduction.html#strings){:.external}, and the basic rules for NumPy indexing.

* indexes start at `0`
* negative indices count backwards from the end
* colons, `:`, are used for slices: `start:stop:step`


In [16]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print("Second column:", rank_2_tensor[:, 1].numpy())


Second column: [2. 4. 6.]


## Reshaping
The `tf.reshape` operation is fast and cheap as the underlying data does not need to be duplicated

In [17]:
x = tf.constant([[1], [2], [3]])
reshaped = tf.reshape(x, [1, 3])

In [18]:
# You can convert this object into a Python list, too
print(x.shape.as_list())

[3, 1]


In [20]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print('before flattening')
print(rank_3_tensor.shape)
# A `-1` passed in the `shape` argument says "Whatever fits".
print(tf.reshape(rank_3_tensor, [-1]))


before flattening
(3, 2, 5)
tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [21]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1])) # -1 here is the reset of the shape: 2*5

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


Swapping axes in `tf.reshape` does not work; you need `tf.transpose` for that.

## Broadcasting

Unlike a mathematical op, for example, `broadcast_to` does nothing special to save memory.  Here, you are materializing the tensor.

It can get even more complicated.  [This section](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html){:.external} of Jake VanderPlas's book _Python Data Science Handbook_ shows more broadcasting tricks (again in NumPy)

## Ragged Tensor

In [22]:
# A tensor with not a rectangular shape
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")


ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)



# The shape of a tf.RaggedTensor will contain some axes with unknown lengths:
print(ragged_tensor.shape)

ValueError: Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


## String tensors

`tf.string` is a `dtype`, which is to say you can represent data as strings (variable-length byte arrays) in tensors.

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor. See `tf.strings` for functions to manipulate them.

## Sparse tensors

Sometimes, your data is sparse, like a very wide embedding space.  TensorFlow supports `tf.sparse.SparseTensor` and related operations to store sparse data efficiently.

In [23]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
