# Notebook [link](https://www.tensorflow.org/tutorials/quickstart/beginner)

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [6]:
# Load the dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()


# noramalizing the data /255
x_train, x_test = x_train/255.0 , x_test/255.0

print(x_train.shape)
print(type(x_train))

(60000, 28, 28)
<class 'numpy.ndarray'>


In [12]:
# Model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # does not do any thing the out is (578,)
    tf.keras.layers.Dense(128, activation='relu'), # the out size is -> 128
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(10) # withoud activation
])
print(model.input_shape)
print(model.output_shape)

(None, 28, 28)
(None, 10)


# Do not add softmax in the model
softmax is not stable in training (they said so) so we will use the normal output of the model: [logits, or log-odds](https://developers.google.com/machine-learning/glossary#log-odds)  (I don't understand if it perform logits operation on the model or not, but I think it is something related to loss function

In [17]:
# applying the model befre training
predictions = model(x_train[:1]).numpy() # NOte input does not if x_train[0] it has to be list of list
predictions

array([[ 0.10398585, -0.9040525 , -0.78324026,  0.3329395 ,  0.7895306 ,
        -0.92365193, -0.79403746,  1.1994402 ,  1.0322053 ,  0.8122647 ]],
      dtype=float32)

In [19]:
#applying softmax
predictions_soft = tf.nn.softmax(predictions)
predictions_soft

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.0749899 , 0.02736638, 0.03088058, 0.0942836 , 0.14884393,
        0.02683524, 0.03054895, 0.22426042, 0.1897245 , 0.1522665 ]],
      dtype=float32)>

In [22]:
# Loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) # from _logits=True means(not form softmax)

#testing loss function
loss_fn(y_train[:1], predictions).numpy()

3.6180396

In [23]:
# optimizer
model.compile(
    optimizer = 'adam',
    loss= loss_fn,
    metrics=['accuracy']
)

In [24]:
# Train the model
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 6ms/step - loss: 0.3020 - accuracy: 0.9123
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1432 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1054 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0866 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0741 - accuracy: 0.9769


In [25]:
# Evaluating the model
model.evaluate(x_test, y_test, verbose=2)

313/313 - 2s - loss: 0.0677 - accuracy: 0.9792 - 2s/epoch - 5ms/step


[0.06769026815891266, 0.979200005531311]

In [38]:
# adding softmax to the usage of the model
prediction_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])


import numpy as np
x = np.sort(prediction_model(x_test[:1]).numpy())[0][::-1]
x

array([9.9998367e-01, 1.5287715e-05, 7.9397239e-07, 2.7210288e-07,
       1.3112056e-08, 1.2074947e-08, 5.8538498e-09, 1.5043308e-09,
       7.1912300e-13, 6.3504699e-15], dtype=float32)

In [39]:
np.sum(x, axis=0)

1.0